### ISSUE TITLE
Is "" a valid ID if deterministic position strings are desired?

### ISSUE THREAD

**Issue by justjake** [mweidner037/position-strings#2]
My use-case is to migrate data that stores the order of some objects using an array of their UUIDs, to a system where order is determined by lexicographic positions stored as part of each object.

I'd like to make the migration deterministic, so I'm considering using `new PositionSource({ ID: '' })` for the migration, so repeated mappings from the same UUID[] produce the same positions on those objects. I figure `''` is the smallest possible "system ID" we can use.

Once the migration is complete, I think it should be fine for clients (with normal `new PositionSource()`) to start re-ordering those objects without worrying about conflict.

What do you think?

**Comment by mweidner037** [comment]
Yes, that should work: `''` is a valid ID, and results are deterministic once the IDs are fixed.

Internally, `""` gets converted to the "long name" `",."`, where the delimiters `,` and `.` prevent weirdness. There is some test coverage here: https://github.com/mweidner037/position-strings/blob/master/test/manual.test.ts

**Comment by justjake** [comment]
Thanks, very helpful
